version: '3.8'

services:
  frontend:
    image: nginx:latest
    container_name: FE
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
    networks:
      - main
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: BE
    networks:
      - main
networks:
  main:
    driver: bridge
